# Generated by Django 5.1.4 on 2025-01-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('planet_route', models.CharField(max_length=200)),
                ('responsible_person_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('business_nature', models.CharField(max_length=100)),
                ('software', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('modules', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=100)),
                ('licence_type', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
